In [ ]:
FUENTES_DIR = '../Fuentes'         # carpeta donde se encuentran archivos .py auxiliares
DATOS_DIR   = '../Data_Sets/p2/' # carpeta donde se encuentran los datasets

# agrega ruta de busqueda donde tenemos archivos .py
import sys
sys.path.append(FUENTES_DIR)

%matplotlib inline
import numpy as np
import pandas as pd
from matplotlib import pylab as plt
from IPython import display
from ClassPerceptron import Perceptron
from sklearn import preprocessing
import grafica as gr
from ClassNeuronaLineal import NeuronaLineal
from ClassNeuronaGral import *
from sklearn.preprocessing import MinMaxScaler

# Regresión Lineal Múltiple (dos o más variables de entrada)

## Ejercicio 6

Utilice los scripts disponibles en la teoría y práctica para entrenar un combinador lineal.  
El modelo debe recibir tres dígitos binarios y retornar la representación decimal del número que resulta de la combinación de dígitos (para las entradas 000, 010 y 101 debe obtener las salidas 0, 2 y 5, respectivamente).

a) Utilizando el bias o peso W0 (comportamiento normal).  


In [15]:
data = pd.DataFrame({
    "Binarios": [(0,0,0), (0,0,1), (0,1,0), (0,1,1), (1,0,0), (1,0,1), (1,1,0), (1,1,1)],
    "Decimal": [0, 1, 2, 3, 4, 5, 6, 7]
})
ALPHA = 0.1
N_ITER = 1000
COTA_E = 1e-4

X = np.array(data["Binarios"].to_list())
y = np.array(data["Decimal"])

modelo = NeuronaLineal(alpha=ALPHA, n_iter=N_ITER, cotaE=COTA_E, draw=1,
                       title=['Binario', 'Decimal'])
modelo.fit(X, y)
print("\nPesos aprendidos:", modelo.w_)
print("Bias:", modelo.b_)

# Test
for xi, target in zip(X, y):
    print(f"{xi} -> pred: {modelo.predict(xi):.2f}, esperado: {target}")


Pesos aprendidos: [3.99492129 1.99474855 0.99475783]
Bias: 0.01123937330818493
[0 0 0] -> pred: 0.01, esperado: 0
[0 0 1] -> pred: 1.01, esperado: 1
[0 1 0] -> pred: 2.01, esperado: 2
[0 1 1] -> pred: 3.00, esperado: 3
[1 0 0] -> pred: 4.01, esperado: 4
[1 0 1] -> pred: 5.00, esperado: 5
[1 1 0] -> pred: 6.00, esperado: 6
[1 1 1] -> pred: 7.00, esperado: 7


### b) 

Utilizando únicamente las tres entradas correspondientes a los dígitos binarios anulando el bias o W0 del cálculo.  

Compare la cantidad de iteraciones necesarias para obtener el vector de pesos correcto en ambos casos. Observe el valor del arco correspondiente al bias en a).

In [11]:
import numpy as np

from sklearn.preprocessing import MinMaxScaler

ALPHA = 0.05
MAX_ITE = 10000
COTA = 10e-6

X = np.array([[0,0,0],
			[0,1,0],
			[1,0,1]])

T = np.array([[0],
			[2],
			[5]])

data_scaler , targer_scaler= MinMaxScaler(), MinMaxScaler()
X = data_scaler.fit_transform(X)
T = targer_scaler.fit_transform(T)


ng_no_bias = NeuronaGradiente(alpha=ALPHA, n_iter=MAX_ITE, cotaE=COTA, FUN='linear', title=['bits','decimal'], with_bias=False)

ng_no_bias.fit(X, T)

Y_pred = ng_no_bias.predict_nOut(X)
print("Error cuadrático medio sin bias: ", np.mean((T - Y_pred)**2))
print("Iteraciones sin bias:", ng_no_bias.iterations_)
print("Valor del arco del bias: ", ng_no_bias.b_)

Error cuadrático medio sin bias:  0.33813789609063716
Iteraciones sin bias: 84
Valor del arco del bias:  0
